export interface RestaurantSummary {
  id: string;
  name: string;
  slug: string;
  category: string;
  rating: number;
  reviewsCount: number;
  distanceKm: number;
  area: string;
  prepTime: string;
  priceRange: string;
  availableTables: number;
  totalTables: number;
  imageUrl: string;
  tags: string[];
  popularItem: string;
}

export const CATEGORIES = [
  "Semua",
  "Meja Ready",
  "Coffee & Cafe",
  "Asian & Noodle",
  "Steak & Grill",
  "Family Resto",
  "Dessert & Bakery",
  "Fast Food & Burger",
];

export const MOCK_RESTAURANTS: RestaurantSummary[] = [
  {
    id: "1",
    name: "Kopi Kenangan Senopati",
    slug: "kopi-kenangan-senopati",
    category: "Coffee & Cafe",
    rating: 4.8,
    reviewsCount: 142,
    distanceKm: 0.8,
    area: "Senopati, Jaksel",
    prepTime: "10-15 mnt",
    priceRange: "Rp25k - Rp50k",
    availableTables: 6,
    totalTables: 12,
    imageUrl: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80",
    tags: ["Outdoor", "Wi-Fi Cepat", "Stopkontak"],
    popularItem: "Kopi Kenangan Mantan",
  },
  {
    id: "2",
    name: "Bakmi GM Grand Indonesia",
    slug: "bakmi-gm-gi",
    category: "Asian & Noodle",
    rating: 4.9,
    reviewsCount: 380,
    distanceKm: 1.5,
    area: "Thamrin, Jakpus",
    prepTime: "12-18 mnt",
    priceRange: "Rp35k - Rp75k",
    availableTables: 3,
    totalTables: 20,
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    tags: ["Family Friendly", "Halal Certified", "AC"],
    popularItem: "Bakmi Spesial GM Pangsit",
  },
  {
    id: "3",
    name: "Holycow! Steakhouse Senopati",
    slug: "holycow-senopati",
    category: "Steak & Grill",
    rating: 4.7,
    reviewsCount: 215,
    distanceKm: 1.2,
    area: "Senopati, Jaksel",
    prepTime: "18-25 mnt",
    priceRange: "Rp95k - Rp250k",
    availableTables: 0,
    totalTables: 15,
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    tags: ["Wagyu Beef", "Free Refill", "Valet"],
    popularItem: "Prime Rib Eye 200g",
  },
  {
    id: "4",
    name: "Pagi Sore Padang Premium",
    slug: "pagi-sore-kemang",
    category: "Family Resto",
    rating: 4.9,
    reviewsCount: 520,
    distanceKm: 2.3,
    area: "Kemang, Jaksel",
    prepTime: "5-10 mnt",
    priceRange: "Rp50k - Rp150k",
    availableTables: 8,
    totalTables: 25,
    imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
    tags: ["VIP Room", "Parkir Luas", "Keluarga"],
    popularItem: "Ayam Pop & Rendang Daging",
  },
  {
    id: "5",
    name: "Gyu-Kaku Japanese BBQ",
    slug: "gyu-kaku-pim",
    category: "Asian & Noodle",
    rating: 4.9,
    reviewsCount: 460,
    distanceKm: 3.1,
    area: "Pondok Indah, Jaksel",
    prepTime: "15-20 mnt",
    priceRange: "Rp180k - Rp350k",
    availableTables: 4,
    totalTables: 18,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
    tags: ["Buffet BBQ", "Private Table", "Grill"],
    popularItem: "King Karubi & Milk Pudding",
  },
  {
    id: "6",
    name: "Union Brasserie & Bakery",
    slug: "union-plaza-senayan",
    category: "Dessert & Bakery",
    rating: 4.8,
    reviewsCount: 390,
    distanceKm: 1.8,
    area: "Plaza Senayan, Jaksel",
    prepTime: "10-15 mnt",
    priceRange: "Rp75k - Rp200k",
    availableTables: 2,
    totalTables: 16,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    tags: ["Cocktails", "Signature Cake", "Dine In"],
    popularItem: "Red Velvet Cake & Truffle Pasta",
  },
  {
    id: "7",
    name: "Sate Khas Senayan Pakubuwono",
    slug: "sate-khas-senayan",
    category: "Family Resto",
    rating: 4.7,
    reviewsCount: 280,
    distanceKm: 2.0,
    area: "Kebayoran Baru, Jaksel",
    prepTime: "12-18 mnt",
    priceRange: "Rp45k - Rp110k",
    availableTables: 5,
    totalTables: 14,
    imageUrl: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80",
    tags: ["Authentic Nusantara", "Bumbu Kacang", "AC"],
    popularItem: "Sate Ayam Campur Bumbu Kacang",
  },
  {
    id: "8",
    name: "Subway Cilandak Town Square",
    slug: "subway-citos",
    category: "Fast Food & Burger",
    rating: 4.6,
    reviewsCount: 175,
    distanceKm: 3.5,
    area: "Cilandak, Jaksel",
    prepTime: "8-12 mnt",
    priceRange: "Rp38k - Rp85k",
    availableTables: 7,
    totalTables: 10,
    imageUrl: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80",
    tags: ["Fresh Sandwich", "Takeaway Ready", "Quick Bite"],
    popularItem: "Italian B.M.T. 6-inch",
  },
  {
    id: "9",
    name: "Sushi Tei Kelapa Gading",
    slug: "sushi-tei-mkg",
    category: "Asian & Noodle",
    rating: 4.8,
    reviewsCount: 410,
    distanceKm: 5.2,
    area: "Kelapa Gading, Jakut",
    prepTime: "15-20 mnt",
    priceRange: "Rp60k - Rp180k",
    availableTables: 0,
    totalTables: 22,
    imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80",
    tags: ["Sushi Bar", "Fresh Salmon", "Family Table"],
    popularItem: "Salmon Oyako Roll & Chawanmushi",
  },
  {
    id: "10",
    name: "Lawless Burgerbar Kemang",
    slug: "lawless-burger-kemang",
    category: "Fast Food & Burger",
    rating: 4.9,
    reviewsCount: 530,
    distanceKm: 2.7,
    area: "Kemang, Jaksel",
    prepTime: "12-16 mnt",
    priceRange: "Rp65k - Rp130k",
    availableTables: 3,
    totalTables: 12,
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    tags: ["Juicy Patty", "Rock Vibes", "Craft Beers"],
    popularItem: "The Lemmy Double Juicy Patty",
  },
  {
    id: "11",
    name: "Monsieur Spoon PIK Avenue",
    slug: "monsieur-spoon-pik",
    category: "Dessert & Bakery",
    rating: 4.8,
    reviewsCount: 340,
    distanceKm: 6.8,
    area: "Pantai Indah Kapuk, Jakut",
    prepTime: "10-15 mnt",
    priceRange: "Rp40k - Rp120k",
    availableTables: 5,
    totalTables: 18,
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",
    tags: ["French Croissant", "Instagrammable", "Artisan Coffee"],
    popularItem: "Cromboloni Supreme & Almond Croissant",
  },
];
